### ISSUE TITLE
Citizen Not Found Error

### ISSUE THREAD

**Issue by t1a2l** [dymanoid/RealTime#279]
Citizen not found!
   at System.Environment.get_StackTrace()
   at NetNode.RemoveTargetCitizen(UInt16 instanceID, CitizenInstance ByRef data)
   at TouristAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetIndex, Boolean targetIsNode)
   at CitizenAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetBuilding)
   at HumanAI.DMD<DMD<ArriveAtDestination_Patch1>?500834432::ArriveAtDestination_Patch1>(.HumanAI , UInt16 , CitizenInstance ByRef , Boolean )
   at TouristAI.ArriveAtDestination(UInt16 instanceID, CitizenInstance ByRef citizenData, Boolean success)
   at HumanAI.PathfindFailure(UInt16 instanceID, CitizenInstance ByRef data)
   at TrafficManager.Custom.AI.CustomHumanAI.CustomSimulationStep(UInt16 instanceId, CitizenInstance ByRef instanceData, Vector3 physicsLodRefPos)
   at CitizenManager.DMD<DMD<SimulationStepImpl_Patch0>?-238891008::SimulationStepImpl_Patch0>(.CitizenManager , Int32 )
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at CitizenManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Citizen not found!
   at System.Environment.get_StackTrace()
   at NetNode.RemoveTargetCitizen(UInt16 instanceID, CitizenInstance ByRef data)
   at TouristAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetIndex, Boolean targetIsNode)
   at CitizenAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetBuilding)
   at HumanAI.DMD<DMD<ArriveAtDestination_Patch1>?500834432::ArriveAtDestination_Patch1>(.HumanAI , UInt16 , CitizenInstance ByRef , Boolean )
   at TouristAI.ArriveAtDestination(UInt16 instanceID, CitizenInstance ByRef citizenData, Boolean success)
   at HumanAI.PathfindFailure(UInt16 instanceID, CitizenInstance ByRef data)
   at TrafficManager.Custom.AI.CustomHumanAI.CustomSimulationStep(UInt16 instanceId, CitizenInstance ByRef instanceData, Vector3 physicsLodRefPos)
   at CitizenManager.DMD<DMD<SimulationStepImpl_Patch0>?-238891008::SimulationStepImpl_Patch0>(.CitizenManager , Int32 )
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at CitizenManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]
 
(Filename: C:/buildslave/unity/build/artifacts/generated/common/runtime/DebugBindings.gen.cpp Line: 51)

Citizen not found!
   at System.Environment.get_StackTrace()
   at NetNode.RemoveTargetCitizen(UInt16 instanceID, CitizenInstance ByRef data)
   at ResidentAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetIndex, Boolean targetIsNode)
   at CitizenAI.SetTarget(UInt16 instanceID, CitizenInstance ByRef data, UInt16 targetBuilding)
   at HumanAI.DMD<DMD<StartMoving_Patch1>?-1545755520::StartMoving_Patch1>(.HumanAI , UInt32 , Citizen ByRef , UInt16 , UInt16 )
   at RealTime.CustomAI.RealTimeResidentAI`2[[ResidentAI, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[Citizen, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].DoScheduledHome(CitizenSchedule ByRef schedule, .ResidentAI instance, UInt32 citizenId, Citizen ByRef citizen)
   at RealTime.CustomAI.RealTimeResidentAI`2[[ResidentAI, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[Citizen, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].ProcessWaitingForTransport(.ResidentAI instance, UInt32 citizenId, UInt16 instanceId)
   at RealTime.GameConnection.Patches.ResidentAIPatch+ResidentAI_SimulationStep.Postfix(UInt16 instanceID, CitizenInstance ByRef citizenData, .ResidentAI __instance)
   at ResidentAI.DMD<DMD<SimulationStep_Patch1>?-1612002176::SimulationStep_Patch1>(.ResidentAI , UInt16 , CitizenInstance ByRef , Frame ByRef , Boolean )
   at CitizenAI.SimulationStep(UInt16 instanceID, CitizenInstance ByRef data, Vector3 physicsLodRefPos)
   at TrafficManager.Custom.AI.CustomHumanAI.CustomSimulationStep(UInt16 instanceId, CitizenInstance ByRef instanceData, Vector3 physicsLodRefPos)
   at CitizenManager.DMD<DMD<SimulationStepImpl_Patch0>?-238891008::SimulationStepImpl_Patch0>(.CitizenManager , Int32 )
   at SimulationManagerBase`2.SimulationStep(Int32 subStep)
   at CitizenManager.ISimulationManager.SimulationStep(Int32 subStep)
   at SimulationManager.SimulationStep()
   at SimulationManager.SimulationThread()  [Core]

**Comment by dymanoid** [comment]
This issue is not caused by Real Time. It seems that there is some another mod that messes with the citizens instances. A very old version of TMPE had such an issue. Maybe some other mod has it too. The problem is: this exception is only a symptom. The 'real' error happened some time earlier, but it is not know when exactly.

**Comment by t1a2l** [comment]
So it is probably IPT2, waiting for BP response for a few months now...
